### ISSUE TITLE
A few Questions on How does this work Details....

### ISSUE THREAD

**Issue by Illydth** [billyvg/pokemon-journal#35]
Technical details questions if anyone can please answer:

1) Does this stay "logged in" to Niantic's servers after initially pulling the information for pokemon or does it "connect/disconnect" while still displaying the returned data till you "refresh"?

2) When "pulling" data from Niantic's servers, I assume you're just trapping what Niantic's already sending...meaning the client actually gets the exact IV/Stat information, it just doesn't display it?  (you're not issuing...for lack of a better term...special commands to the game server to get this info right?)

3) I assume since you're prompting for google / pokemon.com login info you're telling the Niantic servers you're a POGO client.  What's the possibility of this client being detectable as a non-pogo game client?

Obviously, my concern with this is the potential to be banned.  While POGO map scanners are easy to run in that you can abuse non-main accounts, this only makes sense to run with your actual game account, meaning a ban is very bad.

I'm a bit disconcerted that to load up a saved off JSON response file, you're required to be logged in to Niantic's servers...that seems utterly dangerous for something that isn't changing THAT often.  I would think it would be MUCH less detectable (maybe?) if you logged in, pulled the client data and logged out, saving it to a local file, allowing users to browse "off line" all they want.   This is how sites like PGNEXUS operate.

To boot on that, how is your software still working while all the major websites are Down and/or Not Responding to pulls?

Great software, I love the simplicity, it's just cringe worthy to think for all the time I'm browsing my Pokemon's IV through this tool, i'm maintaining an active connection to Niantic's servers.

BTW: If you are being a game client, I assume "location" is required (GPS coordinates I would assume are required to be passed to the server)...how is a static desktop computer getting coordinates to send that aren't going to cause you to look like you're teleporting all over the place the next time you load POGO on your phone?

**Comment by Tivoli** [comment]
1) It issues API requests to the server, there isn't an active connection.

2) The IVs are included in the API response data, so yes all clients, including the game, have the IVs in the data, but the game UI simply chooses not to display those stats.

3) Yes, it's acting as a POGO client and it's entirely possible to detect. There is a risk to being banned using 3rd party tools.

You aren't logged into the Niantic servers, API requests are ephemeral, you simply need a token to make the requests, hence the sign in. But there isn't such a thing as a sign out. PGNEXUS works the exact same way. The cache could be saved locally, but you need a new token when you refresh.

The main difference is where the connections come from, for a website all the requests for everyone's data come from the same IP, with a desktop client like this one the request comes from your IP and only for your data, it's also far less detectable since your computer is connected to a network that your phone is probably connected to as well so requests come from a common location. If you use PGNEXUS then the request for your data comes from for example Oregon. So using PGNEXUS can trigger a flag because it seems like you teleported.

Location isn't required for fetching user data, only for requests to do things like catch pokemon, spin pokestops, etc.

**Comment by Illydth** [comment]
Thank you very much, that's excellent information...and makes a bunch of sense.  In essence it's more risky using something like PGNEXUS from a ban perspective than it is this tool.
